import Head from 'next/head';
import { Inter } from 'next/font/google';
import Beers from '@/components/Beers';
import Navbar from '@/components/Navbar';
import React from 'react';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
 
  return (
    <>
      <Head>
        <title>Create beer App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <React.Fragment>
          <Navbar/>
        </React.Fragment>

      <div>
      <Beers />
      </div>

      </main>
    </>
  )
}
