import Head from 'next/head';
import { Inter } from 'next/font/google';
import Beers, { BeerType } from '@/components/Beers';
import Navbar from '@/components/Navbar';
import React from 'react'; 
import Link from 'next/link'; 


const inter = Inter({ subsets: ['latin'] });



export default function Home(beer: BeerType) {
  return (
    <>
      <Head>
        <title>IMPACT Beer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <React.Fragment>
          <Navbar />
        </React.Fragment>
        <div>
            <Beers />
          
        </div>
      </main>
    </>
  );
}
