import Head from 'next/head';
import { Inter } from 'next/font/google';
import Beers from '@/components/Beers';
import Navbar from '@/components/Navbar';
import React from 'react'; 
import Link from 'next/link'; // Brug Link fra Next.js i stedet for React Router's Link


const inter = Inter({ subsets: ['latin'] });



export default function Home() {
  return (
    <>
      <Head>
        <title>IMPACT Beer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <React.Fragment>
          <Navbar />
        </React.Fragment>
        <div>
          {/* Opret et link til beersiden med ølens ID */}
          <Link href="/[id]" as={`/beerDetailPage/`} >
          <Beers />
          </Link>

          {/* <Link href="/[id]" as={`/beerDetailPage/${beer.id}`} key={beer.id}>
              <a>{beer.name}</a>
            </Link> */}
          
        </div>
      </main>
    </>
  );
}
